---
apiVersion: 1.0.0
metadata:
  generateName: devops-

components:
  - type: cheEditor
    id: eclipse/che-theia/7.27.2
    memoryLimit: 1Gi
  - id: containers/buildah/latest
    type: chePlugin
  - id: eamodio/vscode-gitlens/latest
    type: chePlugin
  - id: ms-kubernetes-tools/vscode-kubernetes-tools/latest
    type: chePlugin
  - id: ms-python/python/latest
    type: chePlugin
  - id: 4ops/terraform/latest
    type: chePlugin
  - id: ms-azuretools/vscode-docker/latest
    type: chePlugin
  - id: puppet/puppet/latest
    type: chePlugin
  - id: randomchance/logstash/latest
    type: chePlugin
  - id: rebornix/ruby/latest
    type: chePlugin
  - id: wholroyd/hcl/latest
    type: chePlugin
  - type: dockerimage
    # this version is used in the plugin
    image: "webcenter/che-devops:latest"
    alias: devops-cli
    memoryLimit: 1Gi
    mountSources: true
    volumes:
      - name: home
        containerPath: /home/dev
